name : build

on:
  push:
    paths:
      - 'assets/**'
      - 'odc_index/**'
      - 'tests/**'
      - '.github/**'


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.6]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Run Shell Linter
      run: |
        sudo apt-get install -y shellcheck
        for a in $(ls assets/*.sh); do shellcheck $a || true ;done

    - name: Run Python Linter
      uses: lgeiger/black-action@master
      with:
        args: ". --check"
    
    - name: Build Docker
      run: |
        docker build -t datacube-index .
